services:
  server:
    image: mammoth/mammoth.server:latest
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    restart: always
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5400:5432"
    volumes:
      - mammoth_data:/var/lib/postgresql/data
    restart: always

volumes:
  mammoth_data:
    driver: local
