// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/projects": {
            "get": {
                "description": "Retrieves a paginated list of projects with their database connections",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "List all projects",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page (default: 10, max: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.PageResponse-schemas_ProjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new project with name and description",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Create a project",
                "parameters": [
                    {
                        "description": "Project JSON",
                        "name": "project",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.ProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/schemas.ProjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/projects/{id}/compare": {
            "get": {
                "description": "initiates schema comparison from the source database to the target database for the specified project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Compare database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.SchemaComparisonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/projects/{id}/dump": {
            "get": {
                "description": "Generates a full SQL dump of the project's target database and sends it as a downloadable file.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Download the database backup (SQL dump) for a project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ColumnChange": {
            "type": "object",
            "properties": {
                "changed_attributes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/models.ColumnInfo"
                },
                "target": {
                    "$ref": "#/definitions/models.ColumnInfo"
                }
            }
        },
        "models.ColumnInfo": {
            "type": "object",
            "properties": {
                "data_type": {
                    "type": "string"
                },
                "default": {
                    "type": "string"
                },
                "is_nullable": {
                    "type": "boolean"
                },
                "is_primary": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.ForeignKeyChange": {
            "type": "object",
            "properties": {
                "changed_attributes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/models.ForeignKeyInfo"
                },
                "target": {
                    "$ref": "#/definitions/models.ForeignKeyInfo"
                }
            }
        },
        "models.ForeignKeyInfo": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "onDelete": {
                    "type": "string"
                },
                "onUpdate": {
                    "type": "string"
                },
                "referencedColumns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "referencedTable": {
                    "type": "string"
                }
            }
        },
        "models.IndexChange": {
            "type": "object",
            "properties": {
                "changed_attributes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/models.IndexInfo"
                },
                "target": {
                    "$ref": "#/definitions/models.IndexInfo"
                }
            }
        },
        "models.IndexInfo": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "is_primary": {
                    "type": "boolean"
                },
                "is_unique": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.SchemaDiff": {
            "type": "object",
            "properties": {
                "summary": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "tables_added": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TableDiff"
                    }
                },
                "tables_modified": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TableDiff"
                    }
                },
                "tables_removed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TableDiff"
                    }
                },
                "tables_same": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.TableDiff": {
            "type": "object",
            "properties": {
                "columns_added": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ColumnInfo"
                    }
                },
                "columns_modified": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ColumnChange"
                    }
                },
                "columns_removed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ColumnInfo"
                    }
                },
                "columns_same": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ColumnInfo"
                    }
                },
                "foreign_key_info_added": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ForeignKeyInfo"
                    }
                },
                "foreign_key_info_modified": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ForeignKeyChange"
                    }
                },
                "foreign_key_info_removed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ForeignKeyInfo"
                    }
                },
                "foreign_key_info_same": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ForeignKeyInfo"
                    }
                },
                "indexes_added": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IndexInfo"
                    }
                },
                "indexes_modified": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IndexChange"
                    }
                },
                "indexes_removed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IndexInfo"
                    }
                },
                "indexes_same": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IndexInfo"
                    }
                },
                "table_name": {
                    "type": "string"
                }
            }
        },
        "schemas.DBConnectionRequest": {
            "type": "object",
            "required": [
                "dbname",
                "host",
                "password",
                "port",
                "user"
            ],
            "properties": {
                "dbname": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "schemas.DBConnectionResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "dbname": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "port": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "schemas.PageResponse-schemas_ProjectResponse": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.ProjectResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "schemas.ProjectRequest": {
            "type": "object",
            "required": [
                "name",
                "source",
                "target"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/schemas.DBConnectionRequest"
                },
                "target": {
                    "$ref": "#/definitions/schemas.DBConnectionRequest"
                }
            }
        },
        "schemas.ProjectResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/schemas.DBConnectionResponse"
                },
                "target": {
                    "$ref": "#/definitions/schemas.DBConnectionResponse"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "schemas.SchemaComparisonResponse": {
            "type": "object",
            "properties": {
                "differences": {
                    "$ref": "#/definitions/models.SchemaDiff"
                },
                "migration_script": {
                    "$ref": "#/definitions/services.MigrationScript"
                }
            }
        },
        "services.MigrationScript": {
            "type": "object",
            "properties": {
                "down": {
                    "description": "SQL for reverting changes",
                    "type": "string"
                },
                "up": {
                    "description": "SQL for applying changes",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Mammoth Server API",
	Description:      "This is a database (PostgreSQL) schema comparsion and migration.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
